// <auto-generated />
namespace AppWithUsers4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingtradeNotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingtradeNotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201912181502542_adding tradeNotes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
